name: Terraform Plan

on:
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: TFLint
        uses: terraform-linters/setup-tflint@v4
      - run: tflint --init --config .tflint.hcl
      - run: tflint

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false | tee plan_raw.txt
        env:
          TF_VAR_aws_region: us-east-1

      - name: Save plan output
        if: always()
        run: |
          echo "\n\n---\nTerraform Plan Output\n" > plan.txt
          echo '```' >> plan.txt
          cat plan_raw.txt >> plan.txt || true
          echo '```' >> plan.txt
        shell: bash

      - name: Comment plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: plan.txt
        if: success()
