name: Terraform Plan

on:
  pull_request:
    branches: [ "**" ]

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: mock_access_key
      AWS_SECRET_ACCESS_KEY: mock_secret_key
      AWS_DEFAULT_REGION: us-east-1
      AWS_EC2_METADATA_DISABLED: "true"
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }
      - name: Cache .terraform
        uses: actions/cache@v4
        with:
          path: ./.terraform
          key: ${{ runner.os }}-tf-${{ hashFiles('**/*.tf') }}
      - name: Terraform Fmt
        run: terraform fmt -check -recursive
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Validate
        run: terraform validate
      - name: TFLint Setup
        uses: terraform-linters/setup-tflint@v4
      - name: Run tflint
        run: tflint
      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=tfplan || true
